#!/bin/bash
# nettactoe.sh - Netcat Tic Tac Toe
# Copyright (C) 2024 tusharhero

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if ! command -v clear >/dev/null 2>&1
then
    function clear {
	printf '\033c'
    }
fi

function max {
    [ "$1" -gt "$2" ] && echo "$1" || echo "$2"
}

function min {
    [ "$1" -lt "$2" ] && echo "$1" || echo "$2"
}

function clamp {
    if [ "$1" -lt "$2" ]; then
        echo "$2"
    elif [ "$1" -gt "$3" ]; then
        echo "$3"
    else
        echo "$1"
    fi
}

function get_row {
    cut -d';' -f "$2" <<< "$1"
}

function get_cell {
    cut -d',' -f "$2" <<< "$1"
}

function get_array_element {
    local array=$1
    local y=$2
    local x=$3
    local row
    row=$(get_row "$array" "$y")
    local element
    element=$(get_cell "$row" "$x")
    echo "$element"
}

function set_array_element {
    local array=$1
    local y=$2
    local x=$3
    local newvalue=$4
    local row
    row=$(get_row "$array" "$y")
    row=$(awk -F "," -v newvalue="$newvalue" -v x="$x" 'BEGIN{FS=OFS=","} {$x=newvalue; print}' <<< "$row" )
    array=$(awk -F ";" -v newvalue="$row" -v y="$y" 'BEGIN{FS=OFS=";"} {$y=newvalue; print}' <<< "$array")
    echo "$array"
}

function render_array {
    printf "$(sed -e 's/,//g' -e 's/;/\\n/g' <<< "$1")\n"
}

function check_game {
    local array=$1
    for y in {1..3}; do
	[ "$(get_array_element "$array" "$y" 1)" == "⬛️" ] || \
	    { [ "$(get_array_element "$array" "$y" 1)" == "$(get_array_element "$array" "$y" 2)" ] && \
		  [ "$(get_array_element "$array" "$y" 2)" == "$(get_array_element "$array" "$y" 3)" ] && \
		  { printf '%s' "$(get_array_element "$array" "$y" 1)"; return 0; } }
    done
    for x in {1..3}; do
	[ "$(get_array_element "$array" 1 "$x")" == "⬛️" ] || \
	    { [ "$(get_array_element "$array" 1 "$x")" == "$(get_array_element "$array" 2 "$x")" ] && \
		  [ "$(get_array_element "$array" 2 "$x")" == "$(get_array_element "$array" 3 "$x")" ] && \
		  { printf '%s' "$(get_array_element "$array" 1 "$x")"; return 0; } }
    done
    [ "$(get_array_element "$array" 2 2)" == "⬛️" ] || \
	{ { [ "$(get_array_element "$array" 1 1)" == "$(get_array_element "$array" 2 2)" ] && \
		[ "$(get_array_element "$array" 2 2)" == "$(get_array_element "$array" 3 3)" ]; } || \
	      { [ "$(get_array_element "$array" 3 1)" == "$(get_array_element "$array" 2 2)" ] && \
		    [ "$(get_array_element "$array" 2 2)" == "$(get_array_element "$array" 1 3)" ]; } && \
		  { printf '%s' "$(get_array_element "$array" 2 2)"; return 0; }; }

    [ "$(printf '%s' "$array" | sed 's/[^⬛]//g' | wc --chars)" == '0' ] && { printf 'no one'; return 0;}
}

function make_move {
    local game=$1
    local player=$2
    local move=$3

    local y
    y=$(cut -d"," -f 1 <<< "$move")
    y=$(clamp "$y" 1 3)

    local x
    x=$(cut -d"," -f 2 <<< "$move")
    x=$(clamp "$x" 1 3)

    block="$(get_array_element "$game" "$y" "$x")"
    if [ "$block" == "⭕" ] || [ "$block" == "❌" ]; then
	read -rp "That block is preoccupied, please enter new move: " move
	make_move "$game" "$player" "$move"
    else
	set_array_element "$game" "$y" "$x" "$player"
    fi
}

function restart_game {

    [ -z "$result" ] && return 0
    clear
    render_array "$game"
    echo "$result" won!
    read -rp 'Do you want to play again? [y/N] ' restart

    if [ "$restart" == 'Y' ] || [ "$restart" == 'y' ]; then
	echo 'restarting game!'
	game="$new_game"
	no_moves=0
    else
	exit
    fi
}

function toss {
    if [ "$player_no" -eq 0 ]; then
        move_no=$((RANDOM % 2))
        stdbuf -oL echo "$move_no" >&"${CONN[1]}"
    else
        read -r move_no <&"${CONN[0]}"
    fi
}

function server {
    read -rp "Enter the IP address of the nettactoe server (enter self to host it yourself): " -i "self" -e server_ip
    read -rp "Enter the port of nettactoe server (or the port to use for the nettactoe server): " -i "4444" -e server_port

    if [ "$server_ip" = 'self' ]; then
        coproc SERVER { stdbuf -oL nc -l -p $server_port ; }

        # Read the dummy secret phrase sent by the client.
        # It isn't used because there is no intermediate relay server.
        read <&"${SERVER[0]}"
    else
        read -rp "Enter the shared secret phrase: " -e secret
        coproc SERVER { stdbuf -oL nc "$server_ip" "$server_port"; }
        sleep 3
        stdbuf -oL echo "$secret" >&"${SERVER[1]}"
    fi

    # Read the connected message from client and send acknowledgement.
    echo "Waiting for a client to join.."
    read <&"${SERVER[0]}"

    echo "Client has joined!"
    stdbuf -oL echo 'You joined' >&"${SERVER[1]}"

    new_game="⬛,⬛,⬛️;⬛️,⬛️,⬛️;⬛️,⬛️,⬛️"
    game="$new_game"
    no_moves=0

    while true; do
        clear
        render_array "$game"
        echo "$game" >&"${SERVER[1]}"

        result=$(check_game "$game")
        restart_game

        player=$( ((no_moves % 2 == 0)) && echo "⭕" || echo "❌" )
        if [ "$player" = "⭕" ]; then
            read -rp "$player Enter move: " move
            game=$(make_move "$game" "$player" "$move");
        else
            echo "Waiting for ❌ to make a move"
            read -r game <&"${SERVER[0]}"
        fi

        no_moves=$((no_moves + 1))
    done
}

function client {
    if [ "$#" = 0 ]; then
        read -rp "Enter the IP address of the nettactoe server: " -i "localhost" -e server_ip
        read -rp "Enter the port of the nettactoe server: " -i "4444" -e server_port
        read -rp "Enter the shared secret phrase: " -e secret

        coproc CONN { stdbuf -oL nc "$server_ip" "$server_port"; }
        sleep 3

        stdbuf -oL echo "$secret" >&"${CONN[1]}"

        # Get the player_no. Player 0 is O and 1 is X.
        read -r player_no <&"${CONN[0]}"
    fi

    toss
    game="$NEW_GAME"

    while true; do
        clear
        render_array "$game"

        result=$(check_game "$game")
        restart_game

        player=$( ((move_no % 2 == 0)) && echo "⭕" || echo "❌" )

        if [ $((move_no % 2)) = "$player_no" ]; then
            read -rp "$player Enter move: " move
            game=$(make_move "$game" "$player" "$move");
            echo "$game" >&"${CONN[1]}"
        else
            echo "Waiting for $player to make a move"
            read -r game <&"${CONN[0]}"
        fi

        move_no=$((move_no + 1))
    done
}

function splash_screen {
    printf "
███    ██ ███████ ████████ ████████  █████   ██████ ████████  ██████  ███████ 
████   ██ ██         ██       ██    ██   ██ ██         ██    ██    ██ ██      
██ ██  ██ █████      ██       ██    ███████ ██         ██    ██    ██ █████   
██  ██ ██ ██         ██       ██    ██   ██ ██         ██    ██    ██ ██      
██   ████ ███████    ██       ██    ██   ██  ██████    ██     ██████  ███████ 
"                                                                              
    printf "Copyright (C) 2024 tusharhero\n\n"
    printf "Hit return to start\n"
    read -r
    clear
}

NEW_GAME="⬛,⬛,⬛️;⬛️,⬛️,⬛️;⬛️,⬛️,⬛️"

splash_screen

cat <<EOL
Start a nettactoe server (client can connect to it): server
Connect to a nettactoe server: client
EOL

read -rp ": " mode
case "$mode" in
    [C,c]* ) client ;;
    [S,s]* ) server ;;
    * ) echo "I don't know what mode you are talking about." ;;
esac
